### ISSUE TITLE
How to Add + Sign to Numbers Bigger Than 0

### ISSUE THREAD

**Issue by Behseini** [istvan-ujjmeszaros/bootstrap-touchspin#103]
I am able to get a range  between -6 to 6. The code is handling the - minus sign when the range is under 0 but I need to have + sign also when the numbers are bigger than 0 and of course no sign for 0.
Can you please let me know how to achieve this?

Thansk

**Comment by istvan-ujjmeszaros** [comment]
You have to use the `callback_before_calculation` and `callback_after_calculation` functions like that:
```javascript
$("input[name='demo_callback']").TouchSpin({
  callback_before_calculation: function(v) {
    return Number(v);
  },
  callback_after_calculation: function(v) {
    if (v >= 0) {
      return '+' + v;
    }
    else return v;
  }
});
```

**Comment by Behseini** [comment]
Thanks a lots
