### ISSUE TITLE
How to Fire Event As Soon As Reaching Max

### ISSUE THREAD

**Issue by Behseini** [istvan-ujjmeszaros/bootstrap-touchspin#104]
Can you please let me know how to update the code in way that can fire an event as soon as the spinner reaches the Max?

For example in [this demo ](http://jsfiddle.net/Behseini/fnhxspma/) I need to console log the Max exactly when user reaches the Max not after second click

The reason that I want to do this is prompting error message for user after trying to pass the Max and if I set the Max to 21 it is already violated the rule and to 19 is still invalid because the 20 is valid number

**Comment by istvan-ujjmeszaros** [comment]
Looking like a bug, thanks for reporting. I am trying to fix it today.

**Comment by istvan-ujjmeszaros** [comment]
Fixed in [v4.7.1](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/releases/tag/v4.7.1)
