### ISSUE TITLE
If min/max or step are set on the original input, touchspin should use them

### ISSUE THREAD

**Issue by chinenual** [istvan-ujjmeszaros/bootstrap-touchspin#109]
I've created a pull request: #108 

Use case / rationale:   I have some pages with several dozen TouchSpin decorated inputs - with about 10 different variations on min/max/step depending on the underlying data type.  It's a lot more convenient to just set them directly in the HTML than to have to create CSS classes to match 10 different jquery selectors, and then 10 different javascript fragments to initialize the spinners properly.

**Comment by istvan-ujjmeszaros** [comment]
This is fixed in v4.5.4, thanks for the contribution @chinenual!
