### ISSUE TITLE
Consider using the actual &minus; HTML code

### ISSUE THREAD

**Issue by LarryAzevedo** [istvan-ujjmeszaros/bootstrap-touchspin#114]
I highly recommend using the actual `&minus;` HTML code instead of just "-".  &minus; is semantically correct and looks a lot better:

**With plain "-"**
<img width="216" alt="hyphen" src="https://user-images.githubusercontent.com/2222751/87709171-dd860080-c771-11ea-8c1b-ec7cba9be3a6.png">

**With \&minus;**
<img width="217" alt="minus" src="https://user-images.githubusercontent.com/2222751/87709188-e2e34b00-c771-11ea-9743-0177417a5f31.png">

**Comment by GrumpyMcGee** [comment]
Wow, yea that looks a lot better. I would love to see that change as well.

**Comment by istvan-ujjmeszaros** [comment]
This was already configurable via the `buttondown_txt` setting, but I have changed the default value to `&minus;` with [6c9f657](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/commit/6c9f6570b73bd29bacb15b1568cb7f61cfb9cded). I will publish a new version later today (planning to include some other fixes). This was a good suggestion, thank you.
