### ISSUE TITLE
number format

### ISSUE THREAD

**Issue by thinkerytim** [istvan-ujjmeszaros/bootstrap-touchspin#24]
Great plugin!
Is it possible to format the numbers, adding commas / periods / spaces to make it easier to read? With large numbers it can be hard to tell.

**Comment by avilink** [comment]
Did anyone succeed in making it work with commas?

**Comment by pennstatephil** [comment]
@avilink I can post an example of what we got working tomorrow

**Comment by avilink** [comment]
That would be a big help, thanks!


Met vriendelijke groet / Best regards,

Avi Levy
Link2Ticket

<http://link2ticket.nl>

2015-01-22 5:11 GMT+01:00 Phil H <notifications@github.com>:

**Comment by pennstatephil** [comment]
@avilink here's a working example:
http://codepen.io/pennstatephil/pen/JoJoeO

note the comma is stripped out when the value first changes, then added back in after the math is done

    //strip commas out
    value = parseFloat(elements.input.val().replace(',', ''));
    ...
    //add commas back in
    elements.input.val(value.toFixed(settings.decimals).toString().replace(/,/g, "").replace(/\B(?=(\d{3})+(?!\d))/g, ","));

Ideally, we'd merge this in and have a "commas" option (simple boolean toggle) to turn this behavior on/off. Maybe someday soon :)

**Comment by avilink** [comment]
Thanks for posting that Phil, but I think I need another workaround though. I need a comma as a decimal separator. The control will allow stepping in 0,10 steps.

**Comment by pjcarly** [comment]
You should really support http://numeraljs.com/

**Comment by YZahringer** [comment]
Anyone have a workaround for this?

**Comment by Vmadmax** [comment]
+1

**Comment by thalescmedeiros** [comment]
I've got tired of not finding any working solution.

Here's one that works: https://codepen.io/thalesmedeiros/pen/pEgoxm

**Comment by OliverFriedrich** [comment]
Perhaps some plugin like [Globalize](https://github.com/jquery/globalize) could be a help in this issue. Before i was using the [jQuery UI Spinner Widget](http://api.jqueryui.com/spinner/) that has this feature and is able to format numbers, dates and currencies by this plugin in a target locale (they call it "culture").

Tickets #78 and #65 also target this issue ...
