### ISSUE TITLE
Submit to jsdelivr

### ISSUE THREAD

**Issue by nooblike** [istvan-ujjmeszaros/bootstrap-touchspin#25]
Hey man, please submit your javascript to the CDN, jsdelivr http://www.jsdelivr.com/ , because i want to grab it from there.

Regards.

**Comment by abishekrsrikaanth** [comment]
:+1:

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by istvan-ujjmeszaros** [comment]
Thanks for the info @jimaek, closing as obsolete.
