### ISSUE TITLE
negative value

### ISSUE THREAD

**Issue by lluisd** [istvan-ujjmeszaros/bootstrap-touchspin#26]
When i have a negative value like value="-1" with min: -1, always appears 0. 

For example:
<input id="time" class="form-control" type="text" value="-1" name="time" style="display: block;"></input>
 displays 0.

and i have this:
$("#time").TouchSpin({
                min: -1,
                max: 360000,
                step: 10,
                decimals: 0,
                boostat: 5,
                maxboostedstep: 10,
                postfix: 'seconds'
            });

**Comment by istvan-ujjmeszaros** [comment]
That is the desired behavior. The value gets rounded to the value that is divisible by step.
