### ISSUE TITLE
Option to exclude buttons from tabbing

### ISSUE THREAD

**Issue by smerik** [istvan-ujjmeszaros/bootstrap-touchspin#27]
It would be nice to have an option to exclude the up & down button from tabbing so users who are filling forms manually can speed up when tabbing from field to field.

This of course can be done by adding the attribute tabindex="-1" to the button element.

**Comment by budik21** [comment]
The same problem at me. I have solved it by a workaround, I have added 

    tabindex="-1"

to all occurrences of 

    <button

in javascript source code.

I know, it's not good solution, but sufficient for me and for now.

**Comment by TravisHiscock** [comment]
Updated my 'jquery.bootstrap-touchspin.js' with the tabindex idea, perfect solution.  As these buttons are 'touch spinners', they should have tabindex="-1" as default IMHO.

**Comment by jbuckshin** [comment]
like budik21's solution, but more targeted:
$('.bootstrap-touchspin-down,.bootstrap-touchspin-up').attr('tabindex', -1);

**Comment by seldimi** [comment]
Would be good if there would be an option on TouchSpin about it

**Comment by istvan-ujjmeszaros** [comment]
I agree that tabindex should be disabled by default. Done in [v4.7.3](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/releases/tag/v4.7.3)
