### ISSUE TITLE
multiple touchspin instances with one initialize?

### ISSUE THREAD

**Issue by MartinP7r** [istvan-ujjmeszaros/bootstrap-touchspin#39]
would it be possible to initialize the touchspin once and have it being the same for every instance of the target element (e.g. by class)?

something like:

``` javascript
$("input.classname").TouchSpin({
    min: 1,
    max: 999,
    stepinterval: 50,
    maxboostedstep: 10000000
});
```

I tried around, but all attempts led to a broken touchspinner, so far.

**Comment by piMyHome** [comment]
Try this one, should work:

```
$("input[class='classname']").TouchSpin({
    min: 1,
    max: 999,
    stepinterval: 50,
    maxboostedstep: 10000000
});
```
