### ISSUE TITLE
conclusion after the spinner

### ISSUE THREAD

**Issue by samerset** [istvan-ujjmeszaros/bootstrap-touchspin#42]
Hi!

How to make a conclusion after the spinner value multiplied by the number?

For example, the number of items multiplied by their value:
- 1 + $ 100
- 2 + $ 200
- 10 + $ 1000

![2015-02-13 09 58](https://cloud.githubusercontent.com/assets/10988891/6183563/99268fdc-b367-11e4-9170-02029a4c179f.png)

**Comment by istvan-ujjmeszaros** [comment]
You can use a callback function set with `callback_after_calculation` to use the value.
