### ISSUE TITLE
"value" overridden by "min"

### ISSUE THREAD

**Issue by mtnbikingmom** [istvan-ujjmeszaros/bootstrap-touchspin#43]
I'm setting my value as 0 but it is being overridden by my min setting of 5. Is there a way to show initial setting of 0, then first step starts out with min of 5? Right now the initial value shows 5.

**Comment by netraagal** [comment]
If you want to display 0, then you have to set the min to 0.
Then, if you want to increment from 5 to 5, you use the step parameter
Else, if you only want the first click to do +5, you have to develop the js block to do it.
