### ISSUE TITLE
Request for main to be added to bower

### ISSUE THREAD

**Issue by wjehring** [istvan-ujjmeszaros/bootstrap-touchspin#44]
Would it be possible to add the main file into the bower file? I'm using wiredep to inject sources and it's not injecting bootstrap-touchspin because you don't have a 'main' key in the bower file (this would normally point to the dist js file). Thanks!

**Comment by mcianc** [comment]
Me too, why is not published on bower repository?

**Comment by istvan-ujjmeszaros** [comment]
Closing as `main` was defined in `bower.json` since this issue was opened. Feel free to reopen if there still is any issue with bower.
