### ISSUE TITLE
bug in your _getBoostedStep() 

### ISSUE THREAD

**Issue by Symannek** [istvan-ujjmeszaros/bootstrap-touchspin#45]
hi, i believe this must be a bug in your _getBoostedStep() function.
wrong results with spinning up: 23, 43, 73, 93, 113 ...
correct results would be: 23, 46, 69, 92, 115 ...
The are uncorrect values with spinning down too.

<input id="demo1" type="text" value="23" name="demo1">

<script>
    $("input[name='demo1']").TouchSpin({
        min: 23,
        max: 10000,
        step: 23,
        decimals: 0,
        boostat: 5,
        maxboostedstep: 10,
        postfix: '$'
    });
</script>

**Comment by istvan-ujjmeszaros** [comment]
This should be fixed in a recent version, feel free to reopen if there still is an error.
