### ISSUE TITLE
Disable Touchspin

### ISSUE THREAD

**Issue by abhishekgupta1991** [istvan-ujjmeszaros/bootstrap-touchspin#46]
I want disable touchspin on the start. After I checked my checkbox, touchspin is enabled.
How I can disable touchspin.

**Comment by celeneisip** [comment]
+1

**Comment by istvan-ujjmeszaros** [comment]
This is fixed in [v4.5.2](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/releases/tag/v4.5.2)
