### ISSUE TITLE
Improperly handles placement and formatting on input-group with existing input-group-addon

### ISSUE THREAD

**Issue by robross0606** [istvan-ujjmeszaros/bootstrap-touchspin#48]
When attempting to add spinner features to an input-group that has an input-group-addon, on off multiple bad things happen depending upon the passed in settings.  If verticalbuttons are set, input-group with an existing add-on get regular horizontal buttons.  Regular horizontal button CSS also incorrectly rounds the wrong corners and doesn't properly adjust the margins.

**Comment by istvan-ujjmeszaros** [comment]
This is fixed in v4.7.0
