### ISSUE TITLE
No option to change look of standard + and - buttons.

### ISSUE THREAD

**Issue by robross0606** [istvan-ujjmeszaros/bootstrap-touchspin#49]
There are options for verticalupclass and verticaldownclass, but nothing similar for adjusting regular left and right buttons?

**Comment by Haixing-Hu** [comment]
Yes, the standard "+" and "-" looks very ugly. It should be replaced by the `glyphicon-plus` and `glyphicon-minus`.

**Comment by Haixing-Hu** [comment]
The master branch has added options "buttonup_txt" and "buttondown_txt" to specify the text content of the up/down buttons.  

But the package registered in bower has not been updated to the recent changes.

**Comment by istvan-ujjmeszaros** [comment]
Thanks, I made a new release.
