### ISSUE TITLE
Consider to focus input when user touches buttons - or +

### ISSUE THREAD

**Issue by rogelio-blanco** [istvan-ujjmeszaros/bootstrap-touchspin#51]
This will be valueable when you need to validate the input with jquery validation.    When I have the input with validation rules, and I get an error the error doesn't go away when I click + or - buttons, however when I click the input to put the focus on it and when move to the next field in the form the error goes away.

So, my recommendation is to focus the input always when the user clicks - or +.  If you do that it will be compatible with jquey validation plugin.

Thanks in advance

**Comment by istvan-ujjmeszaros** [comment]
Thanks for the suggestion, will do that.

**Comment by Lorthirk** [comment]
Please make it optional. Requesting the focus would mean the on screen keyboard showing up on mobile, moving the screen around and resulting in a bad user experience. I moved away from another jQuery UI spinner implementation for this very reason.

**Comment by istvan-ujjmeszaros** [comment]
Agree, that wouldn't be a good solution. It is better to trigger the validator's update from touchspin's change event so I am closing this.
