### ISSUE TITLE
Register on npmjs.org

### ISSUE THREAD

**Issue by sagikazarmark** [istvan-ujjmeszaros/bootstrap-touchspin#53]
Would be nice if people could install it with npm as well.

**Comment by mgwalker** [comment]
Forked and published to npm:  http://npm.im/bootstrap-touchspin

**Comment by graingert** [comment]
@mgwalker what version is 3.1.0 on NPM?

**Comment by graingert** [comment]
@istvan-ujjmeszaros can you take over the NPM project?

**Comment by mgwalker** [comment]
3.0.1.  I will gladly add whoever wants to take it over as a collaborator on npm and then remove myself.

**Comment by graingert** [comment]
@mgwalker is it possible to match the versions?

**Comment by mgwalker** [comment]
I mean, I can update the `bower.json` in the version on npm, but the version on bower will still be the same.  I guess it'd at least be consistent, though.

**Comment by graingert** [comment]
we'd have to get @istvan-ujjmeszaros to update his version in bower.json

**Comment by istvan-ujjmeszaros** [comment]
So I only have to update `bower.json` and make a new release and it will be fine?

**Comment by mgwalker** [comment]
I've added #59 that adds the version bumps I made in the fork, if that would simplify things for you.

**Comment by graingert** [comment]
No, you need to bump the package.json version too. And do another npm
publish

**Comment by istvan-ujjmeszaros** [comment]
@mgwalker can you do the `npm publish` with the new version?

**Comment by mgwalker** [comment]
There's no way to update a published version in npm.  The only way to get the updated `bower.json` into npm is to bump the version again.

Since the only thing that changed from the last time it was published to npm is the `bower.json`, I'd recommend not worrying about updating it now.  It can be synced properly the next time there's an actual change to the code.  It's a pretty minor discrepancy that I don't think will affect many people.

**Comment by istvan-ujjmeszaros** [comment]
Okay, so I made a new (I hope proper) release, v3.1.1

**Comment by mgwalker** [comment]
I've published the latest to npm.  Do you have an npm account?  If so, I'll make you an owner so you don't have to rely on me.  :)

**Comment by istvan-ujjmeszaros** [comment]
Yes, thanks, `istvan-ujjmeszaros`

**Comment by mgwalker** [comment]
There you go!  https://www.npmjs.com/package/bootstrap-touchspin  Feel free to remove me as a collaborator if you'd like, and thanks for taking the effort to get this sorted out.  :smile:

**Comment by istvan-ujjmeszaros** [comment]
Thanks, in fact, I am looking for collaborators for all of my open source projects, so I have no problem with it.
