### ISSUE TITLE
How to validate the value

### ISSUE THREAD

**Issue by abstractindia** [istvan-ujjmeszaros/bootstrap-touchspin#56]
I am using bootstrap validation plugin (https://github.com/formvalidation/formvalidation.io) How to validate the value of touchspin field?

Like the input value must be > 0.
Can you give me an idea?

**Comment by abstractindia** [comment]
In other words : I have 2 spinners in a form. I want the second one's value to be greater then the first one (dependent spinners) How to get it?

**Comment by ibrahimdolas** [comment]
`var form = document.getElementById('form');
var fv = FormValidation.formValidation(form, {
fields: {
area1: {
validators: {
callback: {
message: 'area1 must be greaterThan area2',
callback: function(input) {
var val = input.value;
var area2 = $('#area2').val();
return val > area2;
}
}
}
}
}
});

$('#area1').on('touchspin.on.stopspin', function() {
fv.revalidateField('area1');
})`

and so on...

**Comment by istvan-ujjmeszaros** [comment]
Please use StackOverflow for support requests.
