### ISSUE TITLE
restrict alpha chars

### ISSUE THREAD

**Issue by eness** [istvan-ujjmeszaros/bootstrap-touchspin#63]
hey there,

it would make sense if user unable to use alpha chars in a decimal spinner field. but right now I can use a-zA-Z when I manually set on the input.

**Comment by bostondevin** [comment]
+1

**Comment by istvan-ujjmeszaros** [comment]
It is always getting converted to a number with <code>Number()</code> which results in <code>0</code> when there is an alpha character used. But I am thinking about adding a setting to enable this restriction.

**Comment by istvan-ujjmeszaros** [comment]
I am closing this as it gets converted when the input is losing focus so it shouldn't be an issue.
You can also initiate the plugin on an `<input type="number">` to disable non-numeric inputs altogether.
