### ISSUE TITLE
decimal divider "," for locale (IT)

### ISSUE THREAD

**Issue by itajackass** [istvan-ujjmeszaros/bootstrap-touchspin#65]
is it possible to accept "," for decimal divider instead of "." ?
For Italy, divisor is ","
Because if i insert "34,12", on focus out it replace with "34.00"

Thanks

**Comment by itajackass** [comment]
i fixed it to convert "," to "." to prevent any damage.
```

function _checkValue() {
        var val, parsedval, returnval;
        val = originalinput.val();
	val = val.replace(",","."); //new
	originalinput.val(val); //new
...
```

**Comment by claudio-silva** [comment]
Support for this would be quite appreciated. Our locale is pt-PT.

**Comment by fredericoregateiro** [comment]
👍  💯

**Comment by istvan-ujjmeszaros** [comment]
Done, see the details in #24.
