### ISSUE TITLE
Vertical Buttons not supported when input is inside a 'input-group'

### ISSUE THREAD

**Issue by zoltansimari** [istvan-ujjmeszaros/bootstrap-touchspin#68]
The _advanceInputGroup function ignores the settings.verticalbuttons and therefore doesn't render as expected.

**Comment by gildegeyndt** [comment]
Still a problem.

**Comment by BrainFeeder** [comment]
yes indeed

**Comment by gg3l** [comment]
I found that, when your input is inside a 'input-group', in order for the Vertical Buttons to work you just need to place the input inside a span.

<div class="input-group">
	<span class="input-group-addon" id="basic-addon1">Label</span>
	<span><input type="text" class="form-control"></span>
</div>

**Comment by markwalet** [comment]
Somebody still has to fix this.

**Comment by istvan-ujjmeszaros** [comment]
Fixed in [v4.7.0](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/releases/tag/v4.7.0)
