### ISSUE TITLE
TouchSpin('destroy') does not work.

### ISSUE THREAD

**Issue by phspies** [istvan-ujjmeszaros/bootstrap-touchspin#70]
I'm using TouchSpin in a fluid interface where fields are added and deleted programmatic. Part of these fields includes TouchSpin controls. Included in the field creation process is the resetting of all TouchSpin controls by removing and initializing them with "destroy" first.

It seems the "destroy" option does not work and was hoping if you had any advise on how to remove the TouchSpin controls from a input?

**Comment by celeneisip** [comment]
+1

**Comment by happyiphone** [comment]
Please?

**Comment by granate20** [comment]
Why you want to destroy?...
review the follow:
+ If you want to delete permanently the item use $('#item').remove();
+ If you call TouchSpin in various cases, you need to asegurate that not use .html in view because if are stablished then broken.

**Comment by celeneisip** [comment]
There are instaces/use cases where you want to bind a touchspin to an event and be able swicth back and forth between input and touchspin

**Comment by sdkcarlos** [comment]
The answer to "Why you want to destroy" is someway obvious ... currently isn't possible to reset the input to its original state, which is necessary sometimes. You can't neither initialize TouchSpin in the same element with different configuration as it will be simply ignored. The only workaround i found to initialize TouchSpin multiple times with different configuration in the same input was cloning the node, empty the container, appending the input again and initializing TouchSpin again.

A lot of unnecesary stuff that could be skipped if we only had a destroy method.

**Comment by fr0z3nfyr** [comment]
Bump!  Any update on implementing `destroy` method? 

I have a case similar to OP where I programatically create (single or multiple - depends on how many foreign_key entries are in DB for the selection) `inputs` based on some other selection on the same form. When the selection is cleared or changed, I remove these `inputs` and regenrate the `inputs` (same or different in number). In such a scenario, at least one element `id` will be same as previous (I use the notation `#MyModel0fieldName`, `#MyModel1fieldName` and so on...). 

I'm worried that if I keep reinitializing touchspin every time, some day it's going to come back and bite me in the a$$ because some event is triggered multiple times (as many times as the plugin was initialized on each `id`).

**Comment by istvan-ujjmeszaros** [comment]
I will look into it in the coming days.

**Comment by nssmart** [comment]
Thank you!
However, it does work for me now.
Well, at least I got my touchspins working.
I'm using Yii2 and loading portions of GridView (that contain touchspin) via ajax.
So I use this for new portions and it works as a charm:

		if ($(this).data('TouchSpin')) {
			$(this).TouchSpin('destroy');
		}
		$(this).TouchSpin(touchSpinConfig);

So I'm not sure whether the problem actually exist. Maybe there is something about the events that @fr0z3nfyr mentioned above - I wouldn't notice since I don't watch any.

Thanks for a great plugin!

**Comment by istvan-ujjmeszaros** [comment]
There are events attached to `$(document)`, which definitely is unnecessarily polluting the global document, as all the TouchSpins are adding their own event there. I am sure one common event will be enough for all the TouchSpins, so I will try to refactor it.

@nssmart, are you sure that destroy is working for you or did I misunderstand something? I am already working on properly implementing the destroy, and it doesn't seem to be easy, so it is interesting if it is working for you already.

**Comment by nssmart** [comment]
Heh, I just checked and actually it doesn't :).

Removed the first 3 lines from the code above, and it kept working.
Apparently that destroy didn't do much.
Inputs, that arrive via ajax, just don't have it initialized yet, so the last line was doing the work, while first three were excessive and useless.

My appologies for confusing you.
Good luck implementing a proper destroyer :).

**Comment by istvan-ujjmeszaros** [comment]
Thanks for the follow up!

**Comment by fr0z3nfyr** [comment]
I tried modifying the library couple times but ended up breaking it one way or the other almost every time and injecting meaningless code the other times. So I finally gave up on my attempts to fix this but I'm still waiting for a commit/push that fixes the issue. 

> I am sure one common event will be enough for all the TouchSpins, so I will try to refactor it

I'm sure, that's the approach I was took initially but failed. I was busy on some other project so didn't bother to fix it anymore.

Glad to know that you are listening and working on fixing it @istvan-ujjmeszaros 

I'll wait for a commit that fixes this and gives us a `destructor` Thanks and cheers!!

**Comment by istvan-ujjmeszaros** [comment]
Done, the usage is `$("input").trigger('touchspin.destroy');` or `$('input', '.bootstrap-touchspin').trigger("touchspin.destroy");` to destroy every instance on a page.

I have removed the global events as I think they shouldn't be required. Maybe they were there to force to stop the spinner when scrolling on devices that doesn't fire the proper event on the buttons in some circumstances, but I am not sure if there were such issue. Anyway if something like that comes up then I will use a cleaner approach.

**Comment by fr0z3nfyr** [comment]
> 
> 
> Excellent! Thanks.
> 
> I will test this

Sorry for just disappearing after promising to test the update. 

I have tested the `destroy` feature and created a [jsfiddle for showcase](https://jsfiddle.net/fr0z3nfyr/wb12cq9L/). Test was a success, I didn't get a chance to test with advanced options or even check the behavior of `$(document)` global listeners yet (as confirmed by you in a [comment above](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/issues/70#issuecomment-381302789)).

_While testing and implementing it in my codebase, I wished there was a straight forward way to check if `bootstrap-touchspin` was initialized on an `input`. At present, I'm checking for `.bootstrap-touchspin` on parent element of the `input`, which I believe is neither standard nor should be recommended._
##### Check if plugin is initialized on a specific input:
```
if($('my-input-id').parent().hasClass('bootstrap-touchspin')) {
  // destroy or do other stuff
}
```
**I believe this issue can now be closed and a new issue for the ability to check if plugin is initialized on an `input`.**


Just for the sake of completeness of this post, I'm sharing the details of the test below.

#### Libraries linked:
```
1. jQuery: 2.2.4
2. Twitter Bootstrap: 3.4.1
3. bootstrap-touchspin: 4.2.5
```
#### HTML:
```
<div class="form-group">
  <input id="my-touchspin1" class="form-control" type="text" />
</div>

<button id="init-touchspin" class="btn btn-primary">
  Init
</button>
<button id="destroy-touchspin"  class="btn btn-danger"disabled>
  Destroy
</button>
```
#### JS:
```
/* Bind click event on init btn */
$('#init-touchspin').on('click', function(e) {
	e.preventDefault();		// optional here
  
  // init touchspin with some basic conf options
  $("#my-touchspin1").TouchSpin({
		min: 0,
		step: 0.001,
		decimals: 3,
		boostat: 5,
		maxboostedstep: 10,
		postfix: 'Mtrs.'
	});
  
  $('#destroy-touchspin').prop('disabled', false);		// enable destroy btn
  $(this).prop('disabled', true);		// disable init btn
});

/* Bind click event on destroy btn */
$('#destroy-touchspin').on('click', function(e) {
	e.preventDefault();		// optional here
  
  $("#my-touchspin1").trigger('touchspin.destroy');		// destroy touchspin
  
  $(this).prop('disabled', true);		// disable destroy btn
  $('#init-touchspin').prop('disabled', false);		// enable init btn
});
```
