### ISSUE TITLE
0 is not prepended to the field when adding decimals consisting of a dot and 2 decimal places.

### ISSUE THREAD

**Issue by Ib01** [istvan-ujjmeszaros/bootstrap-touchspin#71]
0 is not prepended to a field when adding decimals consisting of a dot and 2 decimal places.

if I type .99 in a filed a 0 should be prepended to the front, 0.99, to make the behaviour of the component consistent. this does not happen.

cheers

**Comment by istvan-ujjmeszaros** [comment]
Closing as this seems to work as expected in the latest version.
