### ISSUE TITLE
I can add decimal places to a field that should not have decimal places

### ISSUE THREAD

**Issue by Ib01** [istvan-ujjmeszaros/bootstrap-touchspin#72]
I have configured a field to be an int and not have decimal places and yet i am able to add decimals.

if I add 1.99 to the field this value is appropriately rounded up to 2. however if i add 0.00 to the field the value is not parsed and remains 0.00.

**Comment by FawzyMokhtar** [comment]
I hope this help,
Use ` **step = 0.1**`
`<input id="demo1" type="text" value="55" name="demo1">
<script>
    $("input[name='demo1']").TouchSpin({
        min: 0,
        max: 100,
        **step: 0.1,**
        decimals: 2,
        boostat: 5,
        maxboostedstep: 10,
        postfix: '%'
    });
</script>`

**Comment by istvan-ujjmeszaros** [comment]
Closing as this should work as expected in the latest version.
