### ISSUE TITLE
How to change TouchSpin status to disabled ?

### ISSUE THREAD

**Issue by hiyangguo** [istvan-ujjmeszaros/bootstrap-touchspin#74]
I have a desired TouchSpin status to disabled .In other words I want to it value can't be change. I see the document after ,I have not find options in settings list. Can you tell me how to change this status to disabled?Thank you.

**Comment by iprotsyuk** [comment]
Hi @hiyangguo, I guess it's too late, but maybe others will find my answer helpful. I was also looking for such a feature at some point. I ended up with simply applying `disabled` attribute to my spinbox. If you use jQuery, it can be done with `spinbox.prop('disabled', true);`.

**Comment by celeneisip** [comment]
another related request: https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/issues/46.
gonna upvote here too.

+1.

**Comment by istvan-ujjmeszaros** [comment]
This is fixed in [v4.5.2](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/releases/tag/v4.5.2). The buttons are disabled with a MutationObserver if the input is disabled.
