### ISSUE TITLE
updatesettings with postfix

### ISSUE THREAD

**Issue by Dimigergo** [istvan-ujjmeszaros/bootstrap-touchspin#75]
Hello,

If I use the updatesettings function to set a new postfix string, everything works fine, but the initial postfix string doesn't refresh.

`$("#txtTimeShiftValue").TouchSpin({
        postfix: "week"
    });`

`$("#txtTimeShiftValue").trigger("touchspin.updatesettings", { postfix: "month"});`

Thanks in advance.

**Comment by Dimigergo** [comment]
Anything?

**Comment by jayelkaake** [comment]
Ran into the same issue and had to fix it for myself, so I submitted a PR to fix it: https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/pull/76

**Comment by jayelkaake** [comment]
Merged :). You can close this now.

**Comment by istvan-ujjmeszaros** [comment]
Fixed in b87fa994778f11285975b5013c761b0376fe6f21
