### ISSUE TITLE
Uncaught TypeError: value.toFixed is not a function

### ISSUE THREAD

**Issue by boulepick** [istvan-ujjmeszaros/bootstrap-touchspin#77]
Hi there noticed that when the spin reaches the min value and you click on the minus spin to continue, you will get an error in the console "_**Uncaught TypeError: value.toFixed is not a function**_" at line (https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/blame/master/dist/jquery.bootstrap-touchspin.js#L639). 

Changed line 608 && 644 from 
            value = settings.min;
to 
            value = parseFloat(settings.min);

to fix the issue and not get the errors anymore.

**Comment by marios-theofanous** [comment]
Tried this fix and it works. Thanks a lot!
