### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by mandachuvamg** [istvan-ujjmeszaros/bootstrap-touchspin#78]
Today the component only allows the decimal separator is the point. When the field uses mask with the comma as decimal separator does not work. I suggest a decimalSeparator parameter is created

**Comment by OliverFriedrich** [comment]
Perhaps some plugin like [Globalize](https://github.com/jquery/globalize) could be a help in this issue. Before i was using the [jQuery UI Spinner Widget](http://api.jqueryui.com/spinner/) that has this feature and is able to format numbers, dates and currencies by this plugin in a target locale (they call it "culture").

**Comment by istvan-ujjmeszaros** [comment]
Done, see details in #24.

**Comment by murattyilmaz** [comment]
Hello, same thing again. I can't change decimal seperator anymore.

**Comment by murattyilmaz** [comment]
Still same issue.
