### ISSUE TITLE
Cannot change the current value of a touchspin control

### ISSUE THREAD

**Issue by jueadams** [istvan-ujjmeszaros/bootstrap-touchspin#84]
Hi there,

for a reset to defaults function I need to set all values of all controls of an existing form back to default values. I've tried using the callable event **touchspin.updatesettings** like

`
 $("#rowHeight").trigger("touchspin.updatesettings", {value: 120});
`

with no success. 

In general, the update is working for the settings like:

`
$("#rowHeight").trigger("touchspin.updatesettings", {max: 200});
`

How  can the **current value** (val|value) changed on an existing touchspin control?

Many thanks in advance.

Best regards,
Juergen

**Comment by jueadams** [comment]
Did the following as workaround for the time being:

`
      function changeSettings(newsettings) {

      ...

        // jadams 2017-01-23: Added eval of initval
        var value = '';

        if ( newsettings.initval != null ) {
           value = Number(newsettings.initval);
        } else {
           value = Number(elements.input.val());
        }

        if (value !== '')  elements.input.val(value.toFixed(settings.decimals);
        }
      }
`

**Comment by istvan-ujjmeszaros** [comment]
You can just use the `.val()` jquery method on the input element itself.
