### ISSUE TITLE
Input attribute value is not being updated on stopspin

### ISSUE THREAD

**Issue by celeneisip** [istvan-ujjmeszaros/bootstrap-touchspin#90]
input attribute value is not being updated after touchspin stop, thus $( input ).val( ) and $( input ).('attr') have different values. $( input ).val( ) has the correct value but $( input ).('attr') has the initial value

**Comment by istvan-ujjmeszaros** [comment]
That is not a bug, you can use the onchange event to update the value attribute if you need to do that for some reason.
