### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by BjornMelgaard** [istvan-ujjmeszaros/bootstrap-touchspin#93]

**Comment by lukchojnicki** [comment]
It seems that author doesent support this script anymore. :(

All what we can do is forge this script and make own changes in _advanceInputGroup function. Like below. Also do not load CSS file because BS4 has all what we need. Simply use input group class.



```
function _advanceInputGroup(parentelement) {
        parentelement.addClass('bootstrap-touchspin');

        var prev = originalinput.prev(),
            next = originalinput.next();

        var downhtml,
            uphtml,
            prefixhtml = '<div class="input-group-addon input-group-prepend bootstrap-touchspin-prefix"><span class="input-group-text font-weight-bold">' + settings.prefix + '</span></div>',
            postfixhtml = '<div class="input-group-addon input-group-append bootstrap-touchspin-postfix"><span class="input-group-text font-weight-bold">' + settings.postfix + '</span></div>';

        if (prev.hasClass('input-group-btn')) {
          downhtml = '<button class="' + settings.buttondown_class + ' bootstrap-touchspin-down" type="button">' + settings.buttondown_txt + '</button>';
          prev.append(downhtml);
        }
        else {
          downhtml = '<div class="input-group-btn input-group-prepend"><button class="' + settings.buttondown_class + ' bootstrap-touchspin-down" type="button">' + settings.buttondown_txt + '</button></div>';
          $(downhtml).insertBefore(originalinput);
        }

        if (next.hasClass('input-group-btn')) {
          uphtml = '<button class="' + settings.buttonup_class + ' bootstrap-touchspin-up" type="button">' + settings.buttonup_txt + '</button>';
          next.prepend(uphtml);
        }
        else {
          uphtml = '<div class="input-group-btn input-group-append"><button class="' + settings.buttonup_class + ' bootstrap-touchspin-up" type="button">' + settings.buttonup_txt + '</button></div>';
          $(uphtml).insertAfter(originalinput);
        }

        $(prefixhtml).insertBefore(originalinput);
        $(postfixhtml).insertAfter(originalinput);

        container = parentelement;
      }

      function _buildInputGroup() {
        var html;

        if (settings.verticalbuttons) {
          html = '<div class="input-group bootstrap-touchspin"><span class="input-group-addon bootstrap-touchspin-prefix">' + settings.prefix + '</span><span class="input-group-addon bootstrap-touchspin-postfix">' + settings.postfix + '</span><span class="input-group-btn-vertical"><button class="' + settings.buttondown_class + ' bootstrap-touchspin-up" type="button"><i class="' + settings.verticalupclass + '"></i></button><button class="' + settings.buttonup_class + ' bootstrap-touchspin-down" type="button"><i class="' + settings.verticaldownclass + '"></i></button></span></div>';
        }
        else {
          html = '<div class="input-group bootstrap-touchspin"><span class="input-group-btn"><button class="' + settings.buttondown_class + ' bootstrap-touchspin-down" type="button">' + settings.buttondown_txt + '</button></span><span class="input-group-addon bootstrap-touchspin-prefix">' + settings.prefix + '</span><span class="input-group-addon bootstrap-touchspin-postfix">' + settings.postfix + '</span><span class="input-group-btn"><button class="' + settings.buttonup_class + ' bootstrap-touchspin-up" type="button">' + settings.buttonup_txt + '</button></span></div>';
        }

        container = $(html).insertBefore(originalinput);

        $('.bootstrap-touchspin-prefix', container).after(originalinput);

        if (originalinput.hasClass('input-sm')) {
          container.addClass('input-group-sm');
        }
        else if (originalinput.hasClass('input-lg')) {
          container.addClass('input-group-lg');
        }
      }
```

**Comment by istvan-ujjmeszaros** [comment]
Hey @lukchojnicki, it is true that I didn't have time to update my plugins for a very long time. But I plan to update them to bs4, as probably very small changes would be required.
FYI I am fine with adding collaborators to the repository, I have already added some users to some of my other plugins. Are you interested in being a collaborator? Or anyone else?

I don't know what would be a proper approach to make a bs4 version while also maintaining the bs3 version.  Maybe different files for the different bootstrsap versions? Or update the main branch to bs4 and create a bs3 branch to maintain the bs3 version?

**Comment by lukchojnicki** [comment]
I think that it's good enough to just jump from 3.1.2 to 4.0.0 and add to readme information that Bootstrap 3 is supported in version 3 of plugin, and bootstrap 4 version in touchspin 4 version. It's very clear ;) This approach works in many projects.

If You want to keep supporting both versions then maybe touchspin can use both classes from BS3 and BS4 in the same time + with BS4 simply do not load css (also add extra selectors in css to make sure it will not affect input if it was loaded by mistake in BS4)? Not tested.

If You do not have time for this than I can collaborate, but I think that You can change this very quickly like in my previous example.

**Comment by istvan-ujjmeszaros** [comment]
Okay, I will try to update it in the coming week, feel free to bug me if I seem to disappear :)

**Comment by lukchojnicki** [comment]
Any progress ;) ?

**Comment by shaack** [comment]
Hi, I could not wait, but needed one which works with bootstrap 4 for my project. 
Here it is: [bootstrap-input-spinner](https://github.com/shaack/bootstrap-input-spinner)
It has fewer options than this one, but may fit your needs.

**Comment by bonesoul** [comment]
i'm also looking for a bootstrap 4 version :)

**Comment by bonesoul** [comment]
@lukchojnicki do you have a working fork?

**Comment by lukchojnicki** [comment]
@bonesoul only local with ugly changes just to make it work. I can make normal fork today, so You can wait if You want to.

**Comment by bonesoul** [comment]
sure will be great.

i also found these;

https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/vendors/css/forms/spinner/jquery.bootstrap-touchspin.css
https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/vendors/js/forms/spinner/jquery.bootstrap-touchspin.js

**Comment by lukchojnicki** [comment]
@bonesoul and others, have fun ;) I think it should be ok because it works with demo and in my project as well, but feedback is welcomed. If everything is ok then I hope @istvan-ujjmeszaros will merge this.
https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/pull/94

**Comment by djibe** [comment]
Hi,
I created the following fiddle for a Bootstrap 4 evolution : https://jsfiddle.net/djibe89/q25m35ot/
It is developed in a way to simplify js and DOM manipulation and rely on CSS with only 3 classes.

Now a small modification of the js would be sufficient.
But who can do it ????
Thanks for help

**Comment by lukchojnicki** [comment]
Bootstrap 4 now supported. For any issues please create new topic.

**Comment by marcodelpercio** [comment]
Really? Is Bootstrap 4 now supported officially?
