### ISSUE TITLE
Starts spinning when mouse is kept hovering over button after click

### ISSUE THREAD

**Issue by diesl** [istvan-ujjmeszaros/bootstrap-touchspin#96]
I upgraded the touchspin component from 3.x to the latest 4.x release these days and noticed some different behaviour:

3.x:
When clicking the `+` or `-` buttons, they will just increase or decrease the value by the stepsize. When I keep holding the mouse button down, it will start spinning. So far, so good. 

4.x:
When clicking the `+` or `-` buttons, they start spinning when I keep the mouse hovering over the button until I leave the button.

Is this intended behaviour? Personally, I prefer the 3.x way and would at least ask to make it configurable, so that I can disable it.

**Comment by istvan-ujjmeszaros** [comment]
Strange, I don't remember for any changes that could affect it, I think it should stop in v3 too when leaving the button..
I think there were some cases when the browser didn't fire the mouseup event and the spinner didn't stop at all, but I will look into it.

**Comment by istvan-ujjmeszaros** [comment]
Are you guys sure that it was behaving different in the previous versions?
I have just checked back to v2.7.0 from four years ago and it seems to work the same (I don't say that this behavior is good, just want to make sure that we are on the same track).

**Comment by bogdandynamic** [comment]
Personally, I am using the widget for the first time and don't see this as a feature but rather like an unwanted behaviour. The rest of the functionality is excelent and I must congratulate you for your work, but please add a property so that this behaviour can be disabled or enabled. 
Thank you.

**Comment by istvan-ujjmeszaros** [comment]
I think I have misunderstood the issue. I see now that the number keeps spinning after releasing the mouse button. It is definitely a bug.

**Comment by diesl** [comment]
Just came back online and there is already a fixed version. Thank you very much for your quick response!
I can confirm that the bug is fixed in version 4.2.5 👍
