### ISSUE TITLE
Decimal places are lest when using forcestepdivisibility: 'none'

### ISSUE THREAD

**Issue by Misiu** [istvan-ujjmeszaros/bootstrap-touchspin#98]
Hi there,
I'm new to this project but I noticed that decimal places are removed when I use `forcestepdivisibility: 'none'` and `min`.

I have this config:
```
$("#demo0").TouchSpin({
  min: 15000,
  max: 16000,
  step: 100,
  decimals: 2,
  boostat: 5,
  maxboostedstep: 10,
  postfix: '$',
  forcestepdivisibility: 'none'
});
```
as You can see I have min value set to 15000 (that is displayed as `15000.00`), if I click on that field and enter 12 after clicking away value should be presented as `15000.00`

Demo: https://jsfiddle.net/Misiu/cj30c0pt/

![touchspin_bug1](https://user-images.githubusercontent.com/1741838/40479795-da282790-5f4c-11e8-8dbd-23db5ac9265f.gif)

Ideally when user enters value outside specified range (min, max) value should be updated including decimals.

I did some tests and it looks like [this line](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin/blob/master/src/jquery.bootstrap-touchspin.js#L544) should be changed from:
```
return value;
```
to:
```
return value.toFixed(settings.decimals);
```

**Comment by MrGabriCavi** [comment]
Hi there,
same issue.
The @Misiu fix in commit worked for me.

Thanks

**Comment by istvan-ujjmeszaros** [comment]
Thanks guys!

**Comment by Misiu** [comment]
@istvan-ujjmeszaros is't been a while, but I'm glad this got fixed.
Do you plan to support/develop this component?
Bootstrap v5 is in development, maybe you could also target that version?

**Comment by istvan-ujjmeszaros** [comment]
I still have very limited time so I can't promise anything, but I am fine with adding anyone as a collaborator. You know what, I am inviting you and @peterwake.
